### ISSUE TITLE
Prepare wiki tutorial

### ISSUE THREAD

**Issue by mhscience** [mhscience/landslides_detection#3]
As Marvin Maverick, I want to use the landslide detection tool to find landslides but I don't know how to start with it.

**Specification:**
Prepare a tutorial for landslides detection usage including;  

- [x] How to get the landslide detection tool up and running;  How to install dependencies and first run of the landslide detection tool.

- [x] How to obtain images from GEE given the geographical coordinates to later use with the landslide detection tool.

**Comment by mhscience** [comment]
- [ ] Prepare readme with pictures and place tutorial on the wiki
